### PR TITLE
Added about page 

### PR DESCRIPTION
**Pull request by HemantBatra873**
Closes issue #22 

# About the PR
Added about page and made it responsive for all devices . Added animations and effects using the framer-motion library . The theme of the about page is consistent with that of the website . 

https://github.com/user-attachments/assets/b1f8c2df-56a2-43ea-87ff-cbaa7ed75dfd

### CODE REVIEW

**Comment by HemantBatra873** [comment]
I am in the process of fixing some issue with deepSource right now so kindly don't merge the branch right now.

**Comment by 4darsh-Dev** [comment]
@HemantBatra873 , 
But the checks for deepsource are passing.

**Comment by 4darsh-Dev** [comment]
let me know when I can merge .. @HemantBatra873

**Comment by HemantBatra873** [comment]
Because I fixed them now

**Comment by HemantBatra873** [comment]
> let me know when I can merge .. @HemantBatra873 

You can merge them now I have fixed the errors.

**Review by 4darsh-Dev — APPROVED** [review]
nice work @HemantBatra873 , 
the UI is looking pretty good 👍🏻 
keep it up

**Pull request merged**
