### PR TITLE
Updated Code of Conduct.md

### PR DESCRIPTION
**Pull request by Nikhil0-3**
Fixes issue #115 
As per the issue #115  I update the file with all require changes

I updated the code of conduct file by making changes in following points -

Our Pledge
Our Standards
Enforcement Responsibilities
Scope
Pull Request Guidelines
Enforcement
Enforcement Guidelines
Attribution
Conclusion

Also , I tried to make ik more interative.
If any further changes required please tell me.
Screenshot 2024-10-22 150057

Screenshot 2024-10-22 150107
Screenshot 2024-10-22 150121
Screenshot 2024-10-22 150126

### CODE REVIEW

**Comment by Nikhil0-3** [comment]
please add the label of level 2 or level 3, it will be a great help from your side.

**Comment by 4darsh-Dev** [comment]
@Nikhil0-3 
it's a documentation change, 
u can get level1 only.

**Review by 4darsh-Dev — APPROVED** [review]
good work

**Comment by Nikhil0-3** [comment]
> @Nikhil0-3 it's a documentation change, u can get level1 only.

okay.
Thank you for giving me an opportunity.

**Comment by Nikhil0-3** [comment]
Please merge it into your repository.

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!

**Pull request merged**
