### PR TITLE
Added animated spin icon for Loading NFTs.. line 

### PR DESCRIPTION
**Pull request by vedantDube**

### CODE REVIEW

**Comment by vedantDube** [comment]
sorry sir, I accidentally closed the old pull request you assigned me
Screenshot 2024-10-21 001617

**Comment by panwar8279** [comment]
Please resolve file conflict issue.

**Comment by 4darsh-Dev** [comment]
@vedantDube 
u have done good work for hasloader
There issue due because we have added a dialog box nd many changes till now, 
so create a fresh branch and sync your forked repo and 
then add the changes I'll merge the pr

**Comment by 4darsh-Dev** [comment]
our approach for fetching nfts has changed, now we're using infura provider to avoid connecting wallet for viewing operations

**Pull request closed without merging**
