### PR TITLE
Added Error Handling for Missing Wallet Connection on Explore Page

### LINKED ISSUE #96: [Bug]: Error handling at explore page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When navigating to the explore page, if the user's wallet is not found, the application continues to load indefinitely without showing an error message. There is no proper error handling in place, which leads to a poor user experience as users are left waiting without any feedback.

**Current Behavior:**
- If the application fails to detect or connect a wallet on the explore page, it continues loading indefinitely.
- There is no feedback or error message displayed to the user.
- No error handling mechanism is in place to stop the loading process and notify the user of the wallet issue.

**Expected Behavior:**
- If the wallet is not found, an appropriate error message should be displayed.
- The loading spinner should stop, and the user should be notified of the issue.
- Error handling should be implemented to manage cases where the wallet is not detected or fails to connect.

**Steps to Reproduce:**
1. Navigate to the explore page without a connected wallet or with an unsupported wallet.
2. Observe the loading spinner continuing indefinitely without any error message.

**Proposed Solution:**
1. Implement error handling for the "Wallet Not Found" case.
   - If the wallet is not detected, display a clear error message like: `Wallet not found. Please connect a valid wallet to explore items.`
2. Stop the loading spinner when the error occurs to avoid infinite loading.
3. Ensure proper fallback behavior so the user can try reconnecting or return to a previous state.

### Add ScreenShots

Screenshot 2024-10-20 at 2 10 52 PM

### What browsers are you seeing the problem on?

Safari

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by IkkiOcean**
### **Description:**

This PR adds error handling to the **Explore** page to account for scenarios where the user has not connected their wallet. Previously, users without a connected wallet would experience issues when trying to explore content, resulting in continuous loading.

### **Changes Made:**

1. **Error Display on Explore Page**:
   - Added a condition to check if the user has a connected wallet. If not, an error message is displayed, informing the user that wallet connection is required to explore the content.
   
2. **Redirect Logic**:
   - If the user attempts to access the Explore page without a wallet connection, they will be redirected to the wallet connection page.

### **Screenshots**:

- Before:
 
Screenshot 2024-10-21 at 9 25 46 PM

- After (with error handling):
  
Screenshot 2024-10-21 at 9 23 24 PM

### **Relevant Issue**:
- Closes #96 

---

### **Checklist**:
- [x] I have tested this feature thoroughly.
- [x] Error handling works as expected.
- [x] Styling is consistent with the app's theme.
- [x] No breaking changes introduced.

### CODE REVIEW

**Review by 4darsh-Dev — COMMENTED** [review]
I've previewed in codespaces, 
view : 
Screenshot 2024-10-22 142343

**Comment by IkkiOcean** [comment]
@4darsh-Dev sir as you can see I have implemented the error handling in the repo. you can check the file I changed. its even working on my local. if its not working on codespace then pls guide me through it as I dont know whats going wrong here

**Comment by IkkiOcean** [comment]
Screenshot 2024-10-22 at 3 07 32 PM

@4darsh-Dev its working on codespace when I looked into it

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!

**Pull request merged**
