### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by neeru24**
I've updated the README file with several enhancements, including:

- Included a table for metrics.
- Added contributor pictures.
- Made other minor changes for clarity and improved presentation.

**Request**
Kindly assign me Level  and merge this pull request.

Thank you!

Screenshot 2024-10-10 212306
Screenshot 2024-10-10 212410

### CODE REVIEW

**Comment by neeru24** [comment]
> I've updated the README file with several enhancements, including:
> 
> - Included a table for metrics.
> - Added contributor pictures.
> - Made other minor changes for clarity and improved presentation.
> 
> **Request**
> Kindly assign me Level  and merge this pull request.
> 
> Thank you!
> 
> Screenshot 2024-10-10 212306
> Screenshot 2024-10-10 212410
> 

@4darsh-Dev 
Can you add labels for GSSoC too? As WoB is completed... I asked from durgesh sir - Program manager of WoB

**Comment by 4darsh-Dev** [comment]
done, 
Do confirm your points from leaderboard.

**Comment by neeru24** [comment]
> done, Do confirm your points from leaderboard.

image
It's not there... Maybe it'll some time, Right?

**Comment by 4darsh-Dev** [comment]
may be, you can also talk to organizer team in case it didn't get counted. 👍🏻

**Comment by neeru24** [comment]
> may be, you can also talk to organizer team in case it didn't get counted. 👍🏻 



Here you've not added any level.. That's why it is not getting counted... Like level1, level2

**Comment by 4darsh-Dev** [comment]
I've already added labels, check your points on leaderboard in PRs section

**Pull request merged**
