### PR TITLE
Added toggle button for light-dark button

### PR DESCRIPTION
**Pull request by Priyanshu282003**
Added toggle button at navbar to light-to dark mode

### CODE REVIEW

**Comment by panwar8279** [comment]
Hi @Priyanshu282003 , please add 30 sec demo video

**Review by 4darsh-Dev — CHANGES_REQUESTED** [review]
@Priyanshu282003 check the vercel preview from PR
https://decentrade-git-fork-priyanshu282-cc3f26-adarsh-mauryas-projects.vercel.app/create
-- you can see that the input fields texts are not properly visible, fix it
-- along with that adjust the dark background color slight fader

**Comment by Priyanshu282003** [comment]
The required changes are done

**Review by 4darsh-Dev — COMMENTED** [review]
see the vercel preview, @Priyanshu282003 
you have changed the /create page colour that's good
but toggle is not happening properly on /create
I'll fix them.

**Pull request merged**
