### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by Dipanita45**
Added the security 

Fixes : #182 

Please merge my pull request and label me level2 
@4darsh-Dev

### CODE REVIEW

**Comment by Dipanita45** [comment]
Level 1

**Comment by Dipanita45** [comment]
Please merge my pull request and label me 
@4darsh-Dev

**Comment by Dipanita45** [comment]
Please merge my pull request and label me
@4darsh-Dev
As today is the last day

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 PA and Mentor nominations have been started for GSSoC-Ext 2k24. '
 Do share your experiences and connect on Socials. '
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions!

**Pull request merged**
