### PR TITLE
ADD Sticky navbar, made it responsive added Hamber DD when on mobile view

### PR DESCRIPTION
**Pull request by shubhagarwal1**
fix: #49 
**Desktop**
Screenshot 2024-10-20 at 8 30 18 PM

**Mobile** 
Screenshot 2024-10-20 at 8 31 08 PM
Screenshot 2024-10-20 at 8 31 25 PM

hey @4darsh-Dev please review my PR

### CODE REVIEW

**Review by 4darsh-Dev — COMMENTED** [review]
good work @shubhagarwal1 , 
It would be much better if you've added the search icon to the left side of ham btn
-- and also adjust font size, color of home page text

**Comment by 4darsh-Dev** [comment]
you can get level3 if you make search icon beside ham btn
and search input opens when a user clicks on it like most of the websites.

**Comment by shubhagarwal1** [comment]
> good work @shubhagarwal1 , It would be much better if you've added the search icon to the left side of ham btn -- and also adjust font size, color of home page text

Hey @4darsh-Dev Thankyou for the feedback, great insights, i can work on improving this, can you please merge this PR,
i will take this as task in my next issues

**Comment by shubhagarwal1** [comment]
> you can get level3 if you make search icon beside ham btn and search input opens when a user clicks on it like most of the websites.

ok, i will start working on this then

**Comment by shubhagarwal1** [comment]
Hey @4darsh-Dev i was not abel to do the improvements suggested for the searchbar, can you please merge this Pr

**Comment by 4darsh-Dev** [comment]
sure

**Pull request merged**
