### PR TITLE
Scroll bar added on website : Suited scroll bar added

### PR DESCRIPTION
**Pull request by VinayLodhi1712**
#164 done

https://github.com/user-attachments/assets/019d2f20-b4ec-4eff-9a1b-684fb3fbde0a

### CODE REVIEW

**Review by 4darsh-Dev — COMMENTED** [review]
@VinayLodhi1712 
any particular reason for adding it in faq.css file
-- 
This is visible in chrome browser but not on firefox : 
### You can verify yrslf
## SS
Screenshot 2024-11-08 155107

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!

**Comment by VinayLodhi1712** [comment]
@4darsh-Dev now you can check it is working on firefox also.
And there are no reason for puttin in faq.css file actually we can place it in any css file but when i will put it in your app.css i dont know why it is not showing i think in app.css css classes are overriding so i have put it in any other file other than app.css it is working.

**Comment by 4darsh-Dev** [comment]
okay np @VinayLodhi1712

**Review by 4darsh-Dev — APPROVED** [review]
fine 👍🏻

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 PA and Mentor nominations have been started for GSSoC-Ext 2k24. '
 Do share your experiences and connect on Socials. '
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions!

**Pull request merged**
