### PR TITLE
added multilanguage support

### LINKED ISSUE #132: [Feature Request]: [Add Multi-Language Support for Global Accessibility]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Implement multi-language support , allowing users from different regions to interact with the website in their preferred language. This feature will enhance accessibility and usability, making it easier for non-English-speaking users to browse the site.

### Use Case

Set up a language selection dropdown or toggle in the header/footer for easy switching.
Store language preferences using cookies or local storage.
Ensure that the translated content adapts dynamically based on the selected language.

### Benefits

_No response_

### Priority

Medium

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a WOB contributor
- [X] I want to work on this issue
- [X] I'm willing to provide further clarification or assistance if needed.

### PR DESCRIPTION
**Pull request by sezallagwal**
closes #132 

please review this pr. Thanks! @4darsh-Dev

### CODE REVIEW

**Comment by sezallagwal** [comment]
can you please review and merge my pr @panwar8279

**Comment by sezallagwal** [comment]
@4darsh-Dev @panwar8279 kindly review my pr, its been 2 days already

**Review by 4darsh-Dev — APPROVED** [review]
nice work @sezallagwal 
sorry for delay I was busy with my tests

**Comment by 4darsh-Dev** [comment]
Gentle Reminder 🚨🚨 
 GSSoC-Ext 24 is going to complete in 2 Days. '
 Complete your assigned Issues and PR reviews before time to get Points on Leaderboard. '
 It was a great experience working with you all, Don't forget to ⭐ star the Repo (only 12 with 62 forks 💔) . 
 Thanks💗 for your valuable contributions!

**Pull request merged**
