### PR TITLE
Added animated spin icon for Loading NFTs.. line

### PR DESCRIPTION
**Pull request by vedantDube**

### CODE REVIEW

**Review by 4darsh-Dev — CHANGES_REQUESTED** [review]
@vedantDube , 
the design for spinner could be better, 
you can use hasloader, or any else from given below:
https://www.davidhu.io/react-spinners/

**Review by 4darsh-Dev — COMMENTED** [review]
@vedantDube you've added the spinner 
but the deployment is failing due to error :
build process is failing because it can't resolve the import for "react-spinners".

## Screenshot
image

**Comment by 4darsh-Dev** [comment]
Try debugging : 
1. Ensure that react spinners are installed
2.  Do a fresh installation 
```bash 
npm cache clean --force
rm -rf node_modules
npm install
```

-- let me know if the error persists

**Comment by vedantDube** [comment]
> Try debugging :
> 
> 1. Ensure that react spinners are installed
> 2. Do a fresh installation
> 
> ```shell
> npm cache clean --force
> rm -rf node_modules
> npm install
> ```
> 
> -- let me know if the error persists

ok sir

**Pull request closed without merging**
